version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - inventory-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  mysql_data: 